#!/usr/bin/env bun
/**
 * scaffold.ts — programmatic implementation of Workflows/ScaffoldFolders.md.
 *
 * Lays down the per-instance four-folder layout for a new agent instance and
 * applies migration 0001 to a fresh state.sqlite. Idempotent: re-running on a
 * fully-scaffolded directory is a no-op (every action is "skipped (exists)").
 * Operator-edited files are never overwritten.
 *
 * CLI:
 *   bun scaffold.ts <instance-dir> --host=<host> --agent=<agent>
 *                                  [--force-fallback] [--strict]
 *
 * Hosts (e.g. forge/agent/scaffold-instance.sh) call this once during install:
 *   bun ~/.config/metafactory/pkg/repos/agent-state/skill/scripts/scaffold.ts \
 *       ~/.config/grove/agents/forge --host=grove --agent=forge
 *
 * Behavior:
 *   - state.sqlite          → opened via lib/db.ts openState() so migrations
 *                             share the canonical runner (idempotent by
 *                             schema_migrations bookkeeping).
 *   - dashboard.md          → header + "no work yet" placeholder; skipped if
 *                             exists.
 *   - CLAUDE.md             → bridge file pointing host CC sessions at the
 *                             right context (host + agent baked in); skipped
 *                             if exists.
 *   - context/repos.md      → "scope" placeholder; skipped if exists.
 *   - context/channels.md   → Discord channels in scope placeholder; skipped
 *                             if exists.
 *   - retros/               → mkdir -p (always safe).
 *
 * Flags:
 *   --strict          fail non-zero if migration 0001 source file is missing,
 *                     instead of letting openState() create an empty database.
 *   --force-fallback  reserved for future use; currently a no-op accepted for
 *                     forward-compat with host scripts.
 *
 * Output: one human-readable line per action to stdout, e.g.
 *   scaffold: created state.sqlite
 *   scaffold: skipped CLAUDE.md (exists)
 *   scaffold: created retros/
 */

import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { parseArgs, requireString } from "./lib/args";
import { MIGRATIONS_DIR, openState } from "./lib/db";

type Action = "created" | "skipped";

function log(action: Action, what: string, reason?: string): void {
  const suffix = reason ? ` (${reason})` : "";
  process.stdout.write(`scaffold: ${action} ${what}${suffix}\n`);
}

function usage(): never {
  process.stderr.write(
    "usage: scaffold.ts <instance-dir> --host=<host> --agent=<agent> [--force-fallback] [--strict]\n",
  );
  process.exit(2);
}

function dashboardTemplate(host: string, agent: string): string {
  return `# ${agent} dashboard

_Host: \`${host}\` · Agent: \`${agent}\`_

> Regenerated by \`RegenerateDashboard\`. Do not hand-edit — manual changes will be overwritten.

## Pending work

_no work yet_

## In flight

_no work yet_

## Recently resolved

_no work yet_
`;
}

function claudeMdTemplate(host: string, agent: string): string {
  return `# CLAUDE.md — ${agent} instance bridge

This file orients Claude Code sessions launched against this agent instance.

- **Host:** \`${host}\`
- **Agent:** \`${agent}\`
- **Instance dir:** this directory (\`MF_INSTANCE_DIR\`)

## State

- \`state.sqlite\` — work_items + events tables. Managed by the AgentState
  bundle's scripts (\`errands.ts\`, \`events.ts\`, \`dashboard.ts\`, \`retro.ts\`).
  Never hand-edit.
- \`dashboard.md\` — generated view of current work. Regenerated by
  \`RegenerateDashboard\`.
- \`retros/\` — weekly ISO-week retro markdown files.
- \`context/repos.md\` — repositories in scope for this agent.
- \`context/channels.md\` — Discord channels this agent monitors.

## How to interact with state

Always go through the AgentState scripts (resolved via the bundle install path),
never raw SQLite:

\`\`\`bash
MF_INSTANCE_DIR=$(pwd) bun <bundlePath>/skill/scripts/errands.ts list
MF_INSTANCE_DIR=$(pwd) bun <bundlePath>/skill/scripts/events.ts tail --limit 20
\`\`\`

## Persona

If a \`persona.md\` lives next to this file, it is the canonical voice for this
agent. Load it before responding.
`;
}

const REPOS_PLACEHOLDER = `# Repositories in scope

_List the repositories this agent owns or watches. One per line, short name first._

- \`example-repo\` — what this repo is and why this agent cares.
`;

const CHANNELS_PLACEHOLDER = `# Discord channels in scope

_List the Discord channels and threads this agent monitors or posts to._

- \`#example-channel\` — purpose.
`;

type ScaffoldResult = {
  instanceDir: string;
  actions: Array<{ kind: Action; what: string; reason?: string }>;
};

export type ScaffoldOptions = {
  instanceDir: string;
  host: string;
  agent: string;
  strict?: boolean;
  forceFallback?: boolean;
};

/**
 * Programmatic entrypoint — useful for tests and for hosts that want to embed
 * the scaffold step rather than spawn a subprocess.
 */
export function scaffold(opts: ScaffoldOptions): ScaffoldResult {
  const { instanceDir, host, agent } = opts;
  const result: ScaffoldResult = { instanceDir, actions: [] };

  const record = (kind: Action, what: string, reason?: string): void => {
    result.actions.push({ kind, what, ...(reason ? { reason } : {}) });
    log(kind, what, reason);
  };

  // 1. Instance dir itself — mkdir -p (no log line if it already exists, that's
  //    expected for partial-state re-runs).
  if (!existsSync(instanceDir)) {
    mkdirSync(instanceDir, { recursive: true });
  }

  // 2. --strict: verify migration 0001 source exists before openState() would
  //    silently fall back to an empty schema. openState() actually throws when
  //    a migration file is missing because loadMigrations() reads the file
  //    eagerly — but in --strict mode we want a clean, scaffold-flavored error
  //    rather than a stack trace from readFileSync.
  //
  //    Tests can point at a fake migrations dir via MF_MIGRATIONS_DIR_OVERRIDE
  //    without disturbing the real bundle layout (which other parallel tests
  //    depend on).
  const migrationsDir = process.env.MF_MIGRATIONS_DIR_OVERRIDE ?? MIGRATIONS_DIR;
  const migration0001 = join(migrationsDir, "0001-initial.sql");
  if (opts.strict && !existsSync(migration0001)) {
    process.stderr.write(
      `scaffold: --strict mode: migration 0001 not found at ${migration0001}\n`,
    );
    process.exit(3);
  }

  // 3. state.sqlite — created (or migrated) via openState(). Note we set
  //    explicit path so MF_INSTANCE_DIR env is not required for this call.
  const statePath = join(instanceDir, "state.sqlite");
  const stateExisted = existsSync(statePath);
  const { db } = openState({ path: statePath });
  db.close();
  if (stateExisted) {
    record("skipped", "state.sqlite", "exists");
  } else {
    record("created", "state.sqlite");
  }

  // 4. dashboard.md
  const dashboardPath = join(instanceDir, "dashboard.md");
  if (existsSync(dashboardPath)) {
    record("skipped", "dashboard.md", "exists");
  } else {
    writeFileSync(dashboardPath, dashboardTemplate(host, agent));
    record("created", "dashboard.md");
  }

  // 5. CLAUDE.md
  const claudePath = join(instanceDir, "CLAUDE.md");
  if (existsSync(claudePath)) {
    record("skipped", "CLAUDE.md", "exists");
  } else {
    writeFileSync(claudePath, claudeMdTemplate(host, agent));
    record("created", "CLAUDE.md");
  }

  // 6. context/ dir + two placeholders
  const contextDir = join(instanceDir, "context");
  if (!existsSync(contextDir)) {
    mkdirSync(contextDir, { recursive: true });
    record("created", "context/");
  } else {
    record("skipped", "context/", "exists");
  }

  const reposPath = join(contextDir, "repos.md");
  if (existsSync(reposPath)) {
    record("skipped", "context/repos.md", "exists");
  } else {
    writeFileSync(reposPath, REPOS_PLACEHOLDER);
    record("created", "context/repos.md");
  }

  const channelsPath = join(contextDir, "channels.md");
  if (existsSync(channelsPath)) {
    record("skipped", "context/channels.md", "exists");
  } else {
    writeFileSync(channelsPath, CHANNELS_PLACEHOLDER);
    record("created", "context/channels.md");
  }

  // 7. retros/ — mkdir -p, always safe.
  const retrosDir = join(instanceDir, "retros");
  if (!existsSync(retrosDir)) {
    mkdirSync(retrosDir, { recursive: true });
    record("created", "retros/");
  } else {
    record("skipped", "retros/", "exists");
  }

  return result;
}

async function main(): Promise<void> {
  const argv = Bun.argv.slice(2);
  if (argv.length === 0) usage();
  const parsed = parseArgs(argv);
  const instanceDir = parsed.positional[0];
  if (!instanceDir) usage();

  const host = requireString(parsed, "host");
  const agent = requireString(parsed, "agent");
  const strict = parsed.flags["strict"] === true || parsed.flags["strict"] === "true";
  const forceFallback =
    parsed.flags["force-fallback"] === true || parsed.flags["force-fallback"] === "true";

  scaffold({ instanceDir, host, agent, strict, forceFallback });
}

if (import.meta.main) {
  main().catch((err: unknown) => {
    const msg = err instanceof Error ? err.message : String(err);
    process.stderr.write(`scaffold.ts: ${msg}\n`);
    process.exit(1);
  });
}
