#!/usr/bin/env bun
/**
 * scaffold.ts — programmatic implementation of Workflows/ScaffoldFolders.md.
 *
 * Lays down the per-instance four-folder layout for a new agent instance and
 * applies all bundled migrations to state.sqlite. Idempotent: re-running on a
 * fully-scaffolded directory is a no-op (every action is "skipped (exists)").
 * Operator-edited files are never overwritten.
 *
 * CLI:
 *   bun scaffold.ts <instance-dir> --host=<host> --agent=<agent> [--strict]
 *
 * Hosts (e.g. forge/agent/scaffold-instance.sh) call this once during install:
 *   bun ~/.config/metafactory/pkg/repos/agent-state/skill/scripts/scaffold.ts \
 *       ~/.config/grove/agents/forge --host=grove --agent=forge
 *
 * Behavior:
 *   - state.sqlite          → opened via lib/db.ts openState() so migrations
 *                             share the canonical runner (idempotent by
 *                             schema_migrations bookkeeping). When re-run on
 *                             an existing state.sqlite, the output line names
 *                             any newly-applied migrations so operators see
 *                             schema upgrades, not just "(exists)".
 *   - dashboard.md          → header + "no work yet" placeholder; skipped if
 *                             exists.
 *   - CLAUDE.md             → bridge file pointing host CC sessions at the
 *                             right context (host + agent baked in); skipped
 *                             if exists.
 *   - context/repos.md      → "scope" placeholder; skipped if exists.
 *   - context/channels.md   → Discord channels in scope placeholder; skipped
 *                             if exists.
 *   - retros/               → mkdir -p (always safe).
 *
 * Flags:
 *   --strict   fail non-zero if any bundled migration source file is missing
 *              or empty, instead of letting openState() / loadMigrations()
 *              throw a raw readFileSync ENOENT mid-scaffold. Asserts every
 *              file in the bundle's migration list, not just 0001.
 *
 * Output: one human-readable line per action to stdout, e.g.
 *   scaffold: created state.sqlite
 *   scaffold: skipped CLAUDE.md (exists)
 *   scaffold: created retros/
 */

import { existsSync, mkdirSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";

import { parseArgs, requireString } from "./lib/args";
import { getMigrationsDir, listMigrationFiles, openState } from "./lib/db";

type Action = "created" | "skipped";

function log(action: Action, what: string, reason?: string): void {
  const suffix = reason ? ` (${reason})` : "";
  process.stdout.write(`scaffold: ${action} ${what}${suffix}\n`);
}

function usage(): never {
  process.stderr.write(
    "usage: scaffold.ts <instance-dir> --host=<host> --agent=<agent> [--strict]\n",
  );
  process.exit(2);
}

/**
 * `host` and `agent` flow into markdown templates unsanitized. Today's only
 * caller is a trusted host install script, but defense-in-depth: a backtick-
 * or pipe-laced value would render as code blocks / table syntax in
 * dashboard.md and CLAUDE.md. Restrict to the alphanumeric + `_` + `-`
 * shape every real host/agent name uses.
 */
const NAME_PATTERN = /^[A-Za-z0-9_-]+$/;

function validateName(label: string, value: string): void {
  if (!NAME_PATTERN.test(value)) {
    throw new Error(
      `invalid --${label}: ${JSON.stringify(value)} — must match ${NAME_PATTERN.source}`,
    );
  }
}

function dashboardTemplate(host: string, agent: string): string {
  return `# ${agent} dashboard

_Host: \`${host}\` · Agent: \`${agent}\`_

> Regenerated by \`RegenerateDashboard\`. Do not hand-edit — manual changes will be overwritten.

## Pending work

_no work yet_

## In flight

_no work yet_

## Recently resolved

_no work yet_
`;
}

function claudeMdTemplate(host: string, agent: string): string {
  return `# CLAUDE.md — ${agent} instance bridge

This file orients Claude Code sessions launched against this agent instance.

- **Host:** \`${host}\`
- **Agent:** \`${agent}\`
- **Instance dir:** this directory (\`MF_INSTANCE_DIR\`)

## State

- \`state.sqlite\` — work_items + events tables. Managed by the AgentState
  bundle's scripts (\`errands.ts\`, \`events.ts\`, \`dashboard.ts\`, \`retro.ts\`).
  Never hand-edit.
- \`dashboard.md\` — generated view of current work. Regenerated by
  \`RegenerateDashboard\`.
- \`retros/\` — weekly ISO-week retro markdown files.
- \`context/repos.md\` — repositories in scope for this agent.
- \`context/channels.md\` — Discord channels this agent monitors.

## How to interact with state

Always go through the AgentState scripts (resolved via the bundle install path),
never raw SQLite:

\`\`\`bash
MF_INSTANCE_DIR=$(pwd) bun <bundlePath>/skill/scripts/errands.ts list
MF_INSTANCE_DIR=$(pwd) bun <bundlePath>/skill/scripts/events.ts tail --limit 20
\`\`\`

## Persona

If a \`persona.md\` lives next to this file, it is the canonical voice for this
agent. Load it before responding.
`;
}

const REPOS_PLACEHOLDER = `# Repositories in scope

_List the repositories this agent owns or watches. One per line, short name first._

- \`example-repo\` — what this repo is and why this agent cares.
`;

const CHANNELS_PLACEHOLDER = `# Discord channels in scope

_List the Discord channels and threads this agent monitors or posts to._

- \`#example-channel\` — purpose.
`;

type ScaffoldResult = {
  instanceDir: string;
  actions: Array<{ kind: Action; what: string; reason?: string }>;
};

export type ScaffoldOptions = {
  instanceDir: string;
  host: string;
  agent: string;
  strict?: boolean;
};

/**
 * Programmatic entrypoint — useful for tests and for hosts that want to embed
 * the scaffold step rather than spawn a subprocess.
 */
export function scaffold(opts: ScaffoldOptions): ScaffoldResult {
  const { instanceDir, host, agent } = opts;
  validateName("host", host);
  validateName("agent", agent);
  const result: ScaffoldResult = { instanceDir, actions: [] };

  const record = (kind: Action, what: string, reason?: string): void => {
    result.actions.push({ kind, what, ...(reason ? { reason } : {}) });
    log(kind, what, reason);
  };

  // 1. Instance dir itself — mkdir -p (no log line if it already exists, that's
  //    expected for partial-state re-runs).
  if (!existsSync(instanceDir)) {
    mkdirSync(instanceDir, { recursive: true });
  }

  // 2. --strict: verify EVERY bundled migration source exists and is non-empty
  //    before openState() would otherwise throw a raw readFileSync ENOENT mid-
  //    scaffold. Iterates the same MIGRATION_FILES list loadMigrations() reads,
  //    so when 0002 lands the strict precheck automatically extends — no
  //    hardcoded path to forget to update.
  //
  //    Both this precheck and loadMigrations() now read from getMigrationsDir(),
  //    which honors MF_MIGRATIONS_DIR_OVERRIDE — so the env hook exercises the
  //    real production failure mode, not a synthetic shadow path.
  if (opts.strict) {
    const migrationsDir = getMigrationsDir();
    for (const { version, filename } of listMigrationFiles()) {
      const path = join(migrationsDir, filename);
      if (!existsSync(path)) {
        process.stderr.write(
          `scaffold: --strict mode: migration ${version} not found at ${path}\n`,
        );
        process.exit(3);
      }
      // Empty migration file is almost always operator error (truncated copy,
      // bad rebase). loadMigrations() would happily load "" and apply nothing.
      let size = 0;
      try {
        size = statSync(path).size;
      } catch (_err) {
        // statSync after existsSync should not race in practice; treat as missing.
        process.stderr.write(
          `scaffold: --strict mode: migration ${version} not readable at ${path}\n`,
        );
        process.exit(3);
      }
      if (size === 0) {
        process.stderr.write(
          `scaffold: --strict mode: migration ${version} is empty at ${path}\n`,
        );
        process.exit(3);
      }
    }
  }

  // 3. state.sqlite — created (or migrated) via openState(). Note we set
  //    explicit path so MF_INSTANCE_DIR env is not required for this call.
  //    We branch on (existed-before, applied-now) so a re-run that picks up a
  //    NEW migration (e.g. 0002) reports the schema upgrade rather than
  //    silently printing "(exists)".
  const statePath = join(instanceDir, "state.sqlite");
  const stateExisted = existsSync(statePath);
  const { db, applied } = openState({ path: statePath });
  db.close();
  if (stateExisted) {
    if (applied.length > 0) {
      record(
        "skipped",
        "state.sqlite",
        `present, applied ${applied.length} new migration${applied.length === 1 ? "" : "s"}: ${applied.join(", ")}`,
      );
    } else {
      record("skipped", "state.sqlite", "exists");
    }
  } else {
    record("created", "state.sqlite");
  }

  // 4. dashboard.md
  const dashboardPath = join(instanceDir, "dashboard.md");
  if (existsSync(dashboardPath)) {
    record("skipped", "dashboard.md", "exists");
  } else {
    writeFileSync(dashboardPath, dashboardTemplate(host, agent));
    record("created", "dashboard.md");
  }

  // 5. CLAUDE.md
  const claudePath = join(instanceDir, "CLAUDE.md");
  if (existsSync(claudePath)) {
    record("skipped", "CLAUDE.md", "exists");
  } else {
    writeFileSync(claudePath, claudeMdTemplate(host, agent));
    record("created", "CLAUDE.md");
  }

  // 6. context/ dir + two placeholders
  const contextDir = join(instanceDir, "context");
  if (!existsSync(contextDir)) {
    mkdirSync(contextDir, { recursive: true });
    record("created", "context/");
  } else {
    record("skipped", "context/", "exists");
  }

  const reposPath = join(contextDir, "repos.md");
  if (existsSync(reposPath)) {
    record("skipped", "context/repos.md", "exists");
  } else {
    writeFileSync(reposPath, REPOS_PLACEHOLDER);
    record("created", "context/repos.md");
  }

  const channelsPath = join(contextDir, "channels.md");
  if (existsSync(channelsPath)) {
    record("skipped", "context/channels.md", "exists");
  } else {
    writeFileSync(channelsPath, CHANNELS_PLACEHOLDER);
    record("created", "context/channels.md");
  }

  // 7. retros/ — mkdir -p, always safe.
  const retrosDir = join(instanceDir, "retros");
  if (!existsSync(retrosDir)) {
    mkdirSync(retrosDir, { recursive: true });
    record("created", "retros/");
  } else {
    record("skipped", "retros/", "exists");
  }

  return result;
}

async function main(): Promise<void> {
  const argv = Bun.argv.slice(2);
  if (argv.length === 0) usage();
  // Declare --strict boolean so it never greedily consumes the next argv token
  // (e.g. `--strict --host=grove` used to risk capturing `--host=grove` as the
  // strict value depending on token order).
  const parsed = parseArgs(argv, { booleanFlags: ["strict"] });
  const instanceDir = parsed.positional[0];
  if (!instanceDir) usage();

  const host = requireString(parsed, "host");
  const agent = requireString(parsed, "agent");
  const strict = parsed.flags["strict"] === true;

  scaffold({ instanceDir, host, agent, strict });
}

if (import.meta.main) {
  main().catch((err: unknown) => {
    const msg = err instanceof Error ? err.message : String(err);
    process.stderr.write(`scaffold.ts: ${msg}\n`);
    process.exit(1);
  });
}
